const hotels = [
  {
    id: 1,
    name: "Hotel V Nesplein",
    city: "Amsterdam",
    address: "Nes 49, 1012 KD Amsterdam",
    stars: 4,
    pricePerNight: 189,
    rating: 8.9,
    reviewCount: 412,
    description: "Boutique hotel in het hart van Amsterdam, op loopafstand van het Rokin. Karaktervolle kamers met moderne kunst.",
    amenities: ["wifi", "breakfast", "bar", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800",
    hotelWebsiteUrl: "https://hotelv.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/v-nesplein.html",
    lat: 52.3731,
    lng: 4.8965
  },
  {
    id: 2,
    name: "The Dylan Amsterdam",
    city: "Amsterdam",
    address: "Keizersgracht 384, 1016 GB Amsterdam",
    stars: 5,
    pricePerNight: 368,
    rating: 9.2,
    reviewCount: 531,
    description: "Verfijnd grachtenhotel met serene binnentuin, suites in historische panden en een restaurant van topniveau.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800",
    hotelWebsiteUrl: "https://www.dylanamsterdam.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/the-dylan-amsterdam.html",
    lat: 52.3678,
    lng: 4.8839
  },
  {
    id: 3,
    name: "Pulitzer Amsterdam",
    city: "Amsterdam",
    address: "Prinsengracht 323, 1016 GZ Amsterdam",
    stars: 5,
    pricePerNight: 324,
    rating: 9.0,
    reviewCount: 874,
    description: "Een collectie verbonden grachtenhuizen met klassieke salons, rijk textiel en een rustige binnenhof.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "pets"],
    imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    hotelWebsiteUrl: "https://www.pulitzeramsterdam.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/pulitzer.html",
    lat: 52.3732,
    lng: 4.8842
  },
  {
    id: 4,
    name: "Conservatorium Hotel",
    city: "Amsterdam",
    address: "Van Baerlestraat 27, 1071 AN Amsterdam",
    stars: 5,
    pricePerNight: 421,
    rating: 9.1,
    reviewCount: 689,
    description: "Monumentaal muziekhuis naast het Museumplein, met glas, baksteen, wellness en ingetogen luxe.",
    amenities: ["wifi", "breakfast", "restaurant", "pool", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    hotelWebsiteUrl: "https://www.conservatoriumhotel.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/conservatorium.html",
    lat: 52.3582,
    lng: 4.8796
  },
  {
    id: 5,
    name: "Hotel Jakarta Amsterdam",
    city: "Amsterdam",
    address: "Javakade 766, 1019 SH Amsterdam",
    stars: 4,
    pricePerNight: 214,
    rating: 8.8,
    reviewCount: 1260,
    description: "Licht hotel aan het IJ met botanische binnentuin, ruime kamers en uitzicht richting de haven.",
    amenities: ["wifi", "breakfast", "restaurant", "pool", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800",
    hotelWebsiteUrl: "https://hoteljakarta.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/jakarta-amsterdam.html",
    lat: 52.3776,
    lng: 4.9226
  },
  {
    id: 6,
    name: "Sir Albert Hotel",
    city: "Amsterdam",
    address: "Albert Cuypstraat 2-6, 1072 CT Amsterdam",
    stars: 4,
    pricePerNight: 176,
    rating: 8.6,
    reviewCount: 745,
    description: "Stedelijk boutiquehotel in De Pijp met donkere houten details, goede cocktails en musea om de hoek.",
    amenities: ["wifi", "breakfast", "bar", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    hotelWebsiteUrl: "https://www.siralberthotel.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/sir-albert.html",
    lat: 52.3547,
    lng: 4.8885
  },
  {
    id: 7,
    name: "Mainport Hotel Rotterdam",
    city: "Rotterdam",
    address: "Leuvehaven 77, 3011 EA Rotterdam",
    stars: 5,
    pricePerNight: 198,
    rating: 8.7,
    reviewCount: 936,
    description: "Designhotel aan de Maas met skylinekamers, wellness en een ligging tussen haven, musea en bruggen.",
    amenities: ["wifi", "breakfast", "restaurant", "pool", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    hotelWebsiteUrl: "https://www.mainporthotel.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/mainport.html",
    lat: 51.9144,
    lng: 4.4821
  },
  {
    id: 8,
    name: "Hotel New York",
    city: "Rotterdam",
    address: "Koninginnenhoofd 1, 3072 AD Rotterdam",
    stars: 4,
    pricePerNight: 159,
    rating: 8.8,
    reviewCount: 1104,
    description: "Iconisch havenhotel in het voormalige hoofdkantoor van de Holland-Amerika Lijn, vol maritieme historie.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
    hotelWebsiteUrl: "https://hotelnewyork.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/new-york.html",
    lat: 51.9018,
    lng: 4.4848
  },
  {
    id: 9,
    name: "The Slaak Rotterdam",
    city: "Rotterdam",
    address: "Slaak 34, 3061 CS Rotterdam",
    stars: 4,
    pricePerNight: 144,
    rating: 8.5,
    reviewCount: 382,
    description: "Een voormalige drukkerij met moderne kamers, grafische details en een ontspannen restaurant aan de oostkant.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800",
    hotelWebsiteUrl: "https://theslaakrotterdam.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/the-slaak-rotterdam.html",
    lat: 51.9228,
    lng: 4.5019
  },
  {
    id: 10,
    name: "Supernova Hotel",
    city: "Rotterdam",
    address: "s-Gravendijkwal 68, 3014 EG Rotterdam",
    stars: 4,
    pricePerNight: 128,
    rating: 8.7,
    reviewCount: 291,
    description: "Creatief boutiquehotel met lokale kunst, een stille tuin en kamers die warm en eigenzinnig aanvoelen.",
    amenities: ["wifi", "breakfast", "bar", "pets"],
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    hotelWebsiteUrl: "https://supernovahotel.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/supernova.html",
    lat: 51.9155,
    lng: 4.4633
  },
  {
    id: 11,
    name: "The Nox Utrecht",
    city: "Utrecht",
    address: "Keistraat 8, 3512 HV Utrecht",
    stars: 4,
    pricePerNight: 154,
    rating: 8.9,
    reviewCount: 266,
    description: "Kleinschalig stadshotel vlak bij de Dom, met fluweel, warme kleuren en stille kamers boven de oude stad.",
    amenities: ["wifi", "breakfast", "bar", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1554647286-f365d7defc2d?w=800",
    hotelWebsiteUrl: "https://thenoxhotel.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/the-nox.html",
    lat: 52.0921,
    lng: 5.1216
  },
  {
    id: 12,
    name: "Grand Hotel Karel V",
    city: "Utrecht",
    address: "Geertebolwerk 1, 3511 XA Utrecht",
    stars: 5,
    pricePerNight: 211,
    rating: 8.9,
    reviewCount: 724,
    description: "Historisch kloostercomplex met tuinen, royale kamers en een rustige ligging midden in het centrum.",
    amenities: ["wifi", "breakfast", "restaurant", "gym", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800",
    hotelWebsiteUrl: "https://www.karelv.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/grand-karel-v.html",
    lat: 52.0883,
    lng: 5.1171
  },
  {
    id: 13,
    name: "Mother Goose Hotel",
    city: "Utrecht",
    address: "Ganzenmarkt 26, 3512 GE Utrecht",
    stars: 4,
    pricePerNight: 139,
    rating: 8.8,
    reviewCount: 518,
    description: "Eigenzinnig hotel in een historisch hoekpand, met kamers vol karakter en de Oudegracht om de hoek.",
    amenities: ["wifi", "breakfast", "bar"],
    imageUrl: "https://images.unsplash.com/photo-1578681041175-9717c8c5a3e0?w=800",
    hotelWebsiteUrl: "https://www.mothergoosehotel.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/mother-goose.html",
    lat: 52.0924,
    lng: 5.1188
  },
  {
    id: 14,
    name: "Hotel Des Indes",
    city: "Den Haag",
    address: "Lange Voorhout 54-56, 2514 EG Den Haag",
    stars: 5,
    pricePerNight: 238,
    rating: 8.8,
    reviewCount: 921,
    description: "Grande dame aan het Lange Voorhout met marmer, kroonluchters en een gevoel voor Haagse ceremonie.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "pool"],
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    hotelWebsiteUrl: "https://www.hoteldesindes.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/desindes.html",
    lat: 52.0831,
    lng: 4.3157
  },
  {
    id: 15,
    name: "Voco The Hague",
    city: "Den Haag",
    address: "Kneuterdijk 8, 2514 EN Den Haag",
    stars: 4,
    pricePerNight: 152,
    rating: 8.7,
    reviewCount: 608,
    description: "Modern hotel in een voormalig bankgebouw, tussen Noordeinde, musea en de groene Paleistuin.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    hotelWebsiteUrl: "https://thehague.vocohotels.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/voco-the-hague.html",
    lat: 52.0804,
    lng: 4.3076
  },
  {
    id: 16,
    name: "Boulevard Hotel Scheveningen",
    city: "Den Haag",
    address: "Seinpostduin 1, 2586 EA Den Haag",
    stars: 3,
    pricePerNight: 116,
    rating: 8.6,
    reviewCount: 433,
    description: "Klassiek kusthotel boven de boulevard, met uitzicht op zee en een directe tramverbinding naar de stad.",
    amenities: ["wifi", "breakfast", "restaurant", "parking", "pets"],
    imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
    hotelWebsiteUrl: "https://www.boulevardhotel.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/boulevard-scheveningen.html",
    lat: 52.1061,
    lng: 4.2769
  },
  {
    id: 17,
    name: "Kruisherenhotel Maastricht",
    city: "Maastricht",
    address: "Kruisherengang 19-23, 6211 NW Maastricht",
    stars: 5,
    pricePerNight: 245,
    rating: 8.9,
    reviewCount: 654,
    description: "Designhotel in een gotisch klooster, waar glas, staal en eeuwenoude gewelven verrassend natuurlijk samengaan.",
    amenities: ["wifi", "breakfast", "restaurant", "bar", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800",
    hotelWebsiteUrl: "https://www.kruisherenhotelmaastricht.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/kruisherenhotel-maastricht.html",
    lat: 50.8491,
    lng: 5.6856
  },
  {
    id: 18,
    name: "Hotel Beaumont",
    city: "Maastricht",
    address: "Lage Barakken 10, 6221 CJ Maastricht",
    stars: 4,
    pricePerNight: 151,
    rating: 8.7,
    reviewCount: 512,
    description: "Familiehotel in Wyck met ingetogen kamers, goede brasserie en een warme zuidelijke vanzelfsprekendheid.",
    amenities: ["wifi", "breakfast", "restaurant", "bar"],
    imageUrl: "https://images.unsplash.com/photo-1602002418082-dd4f2af2c1d1?w=800",
    hotelWebsiteUrl: "https://www.beaumontmaastricht.com",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/beaumont.html",
    lat: 50.8497,
    lng: 5.6983
  },
  {
    id: 19,
    name: "Brasss Hotel Suites",
    city: "Haarlem",
    address: "Korte Veerstraat 1, 2011 CL Haarlem",
    stars: 5,
    pricePerNight: 172,
    rating: 8.8,
    reviewCount: 237,
    description: "Ruime suites in de oude binnenstad, met warme materialen, badkamers als spa's en de Grote Markt vlakbij.",
    amenities: ["wifi", "breakfast", "bar", "parking"],
    imageUrl: "https://images.unsplash.com/photo-1560448075-bb485b067938?w=800",
    hotelWebsiteUrl: "https://www.brasss.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/brasss-hotel-suites.html",
    lat: 52.3804,
    lng: 4.6366
  },
  {
    id: 20,
    name: "Boutiquehotel Staats",
    city: "Haarlem",
    address: "Ripperdastraat 13A, 2011 KG Haarlem",
    stars: 4,
    pricePerNight: 134,
    rating: 8.9,
    reviewCount: 418,
    description: "Een stijlvol adres nabij station en Spaarne, met botanische details, zachte kamers en een zonnige patio.",
    amenities: ["wifi", "breakfast", "bar", "pets"],
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800",
    hotelWebsiteUrl: "https://www.hotelstaats.nl",
    bookingAffiliateUrl: "https://www.booking.com/hotel/nl/boutiquehotel-staats.html",
    lat: 52.3867,
    lng: 4.6401
  }
];

window.StayNLHotels = hotels;
